######################################################################
# Automatically generated by qmake (2.01a) Thu Oct 6 16:02:48 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Block.h GameBoard.h MainWindow.h PreviewBoard.h
SOURCES += Block.cpp GameBoard.cpp main.cpp MainWindow.cpp PreviewBoard.cpp
