all: main_deque main_rand Palindrome Subset

main_deque: main_deque.cpp
	g++ main_deque.cpp -o main_deque  
main_rand: main_rand.cpp  
	g++ main_rand.cpp -o main_rand  
Palindrome: Palindrome.cpp  
	g++ Palindrome.cpp -o Palindrome  
Subset: Subset.cpp  
	g++ Subset.cpp -o Subset  
