######################################################################
# Automatically generated by qmake (2.01a) Sat Nov 5 12:40:36 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += PointPlotter.h Point.h
SOURCES += PointPlotter.cpp main.cpp
